### ISSUE TITLE
Node contents spill into following nodes

### ISSUE THREAD

**Issue by Thrysoe** [jbn/itikz#26]
* itikz version: 0.1.5
* Python version: 3.8.3
* Operating System: MS Windows 10

### Description

When having multiple cells the node content of the first cell spills into node content of later cells.

### What I Did

```
See image for example.

![node_content_spilling](https://user-images.githubusercontent.com/16900931/110123148-d3784700-7dc0-11eb-9ee4-995eb56e322a.PNG)
```

**Comment by jbn** [comment]
Is this in Jupyter Lab or Notebook? I can't replicate in lab.

![image](https://user-images.githubusercontent.com/78835/110977613-3a44b580-8317-11eb-9ccf-ec8fc460f097.png)

**Comment by Thrysoe** [comment]
It is in Jypyter Notebook. I just tested in Lab as well and had no problems, so that work-around is good enough for me. Thanks!
